'use client';
import React,{useEffect,useRef} from 'react';
import {Bell,CalendarDays,Check,CheckCheck,Clock,FileText,MessageCircle,Stethoscope,X} from 'lucide-react';
import type {CareNotification} from '@/lib/notifications';

type Props={open:boolean;setOpen:(value:boolean)=>void;items:CareNotification[];language:string;translate:(value:string)=>string;onOpen:(item:CareNotification)=>void;onRead:(item:CareNotification)=>void;onReadAll:()=>void;onDismiss:(item:CareNotification)=>void};
const localeFor=(language:string)=>({en:'en-IN',hi:'hi-IN',mr:'mr-IN',bn:'bn-IN',ta:'ta-IN'}[language]||'en-IN');
const iconFor=(type:string)=>type.includes('report')?<FileText size={18}/>:type.includes('case')?<MessageCircle size={18}/>:type.includes('consult')||type.includes('queue')?<Stethoscope size={18}/>:type.includes('appointment')||type.includes('schedule')?<CalendarDays size={18}/>:<Bell size={18}/>;

export default function NotificationPanel({open,setOpen,items,language,translate:t,onOpen,onRead,onReadAll,onDismiss}:Props){
const wrapRef=useRef<HTMLDivElement>(null);const panelRef=useRef<HTMLDivElement>(null);const visible=items.filter(item=>!item.dismissedAt).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));const unread=visible.filter(item=>!item.readAt).length;
useEffect(()=>{if(!open)return;panelRef.current?.focus();const outside=(event:MouseEvent)=>{if(!wrapRef.current?.contains(event.target as Node))setOpen(false)};const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){setOpen(false);(wrapRef.current?.querySelector('.notification-button') as HTMLButtonElement|null)?.focus()}};document.addEventListener('mousedown',outside);document.addEventListener('keydown',key);return()=>{document.removeEventListener('mousedown',outside);document.removeEventListener('keydown',key)}},[open,setOpen]);
const relative=(value:string)=>{const diff=new Date(value).getTime()-Date.now();const abs=Math.abs(diff);const [amount,unit]=abs<60000?[Math.round(diff/1000),'second']:abs<3600000?[Math.round(diff/60000),'minute']:abs<86400000?[Math.round(diff/3600000),'hour']:[Math.round(diff/86400000),'day'];return new Intl.RelativeTimeFormat(localeFor(language),{numeric:'auto'}).format(amount,unit as Intl.RelativeTimeFormatUnit)};
const full=(value:string)=>new Intl.DateTimeFormat(localeFor(language),{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kolkata'}).format(new Date(value))+' IST';
return <div className="notification-wrap" ref={wrapRef}><button className="icon-button notification-button" aria-label={`${t('Notifications')}${unread?` · ${unread} ${t('unread')}`:''}`} aria-haspopup="dialog" aria-expanded={open} onClick={()=>setOpen(!open)}><Bell size={19}/>{unread>0&&<span className="notification-count" aria-hidden="true">{unread>99?'99+':unread}</span>}</button>{open&&<div className="notification-popover" role="dialog" aria-label={t('Notifications')} tabIndex={-1} ref={panelRef}><div className="notification-popover-head"><h2>{t('Notifications')}</h2><button className="text-button" disabled={!unread} onClick={onReadAll}><CheckCheck size={15}/>{t('Mark all read')}</button></div><div className="notification-scroll" role="list">{visible.length?visible.map(item=><article className={`notification-card ${item.readAt?'read':'unread'}`} key={item.id} role="listitem"><button className="notification-main" onClick={()=>onOpen(item)} aria-label={`${item.title}. ${item.message}. ${relative(item.createdAt)}`}><span className="notification-event-icon">{iconFor(item.type)}</span><span className="notification-copy"><span className="notification-title"><strong>{t(item.title)}</strong>{!item.readAt&&<i aria-label={t('Unread notification')}>{t('New')}</i>}</span><span className="notification-message">{item.message}</span><time dateTime={item.createdAt} title={full(item.createdAt)} aria-label={full(item.createdAt)}><Clock size={12}/>{relative(item.createdAt)}</time></span></button><div className="notification-actions">{!item.readAt&&<button onClick={()=>onRead(item)} aria-label={t('Mark as read')} title={t('Mark as read')}><Check size={15}/></button>}<button onClick={()=>onDismiss(item)} aria-label={t('Dismiss notification')} title={t('Dismiss notification')}><X size={15}/></button></div></article>):<div className="notification-empty"><Bell size={27}/><strong>{t('You’re all caught up')}</strong><p>{t('New updates will appear here.')}</p></div>}</div><p className="notification-local-note">{t('Updates are stored on this browser. Background delivery is unavailable while CareSetu is closed.')}</p></div>}</div>}
