'use client';
import React,{useState} from 'react';
import {ArrowLeft,ArrowRight,CalendarDays,HeartPulse,UserPlus} from 'lucide-react';
import {Patient,uid} from '@/lib/medi-data';

export default function RegistrationScreen({onBack,onComplete}:{onBack:()=>void;onComplete:(patient:Patient)=>void}){
  const [name,setName]=useState('');const [phone,setPhone]=useState('');const [dob,setDob]=useState('');const [gender,setGender]=useState('');const [error,setError]=useState('');
  return <main className="auth-page registration-page"><div className="auth-brand"><div className="brand-mark"><HeartPulse size={25}/></div><strong>CareSetu<span>Your story. Better care.</span></strong></div><section className="card auth-card registration-card"><button className="text-button" onClick={onBack}><ArrowLeft size={15}/>Back to entry options</button><div className="question-icon"><UserPlus/></div><span className="eyebrow">NEW PATIENT PROFILE</span><h1>Create your CareSetu profile</h1><p>Add your details once, then continue to your patient portal.</p><label className="field"><span>Full name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Ishant Kumar" required/></label><label className="field"><span>Mobile number</span><input value={phone} onChange={e=>setPhone(e.target.value)} inputMode="tel" placeholder="10-digit number" required/></label><div className="form-grid"><label className="field"><span>Date of birth</span><input type="date" value={dob} onChange={e=>setDob(e.target.value)} required/></label><label className="field"><span>Gender</span><select value={gender} onChange={e=>setGender(e.target.value)} required><option value="">Select</option><option>Female</option><option>Male</option><option>Non-binary</option><option>Prefer not to say</option></select></label></div>{error&&<p className="error">{error}</p>}<button className="button" onClick={()=>{if(!name.trim()||phone.replace(/\D/g,'').length<10||!dob||!gender){setError('Complete each field to create your profile.');return}const clean=name.trim();const initials=clean.split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase();const age=Math.max(0,new Date().getFullYear()-new Date(dob).getFullYear()-(new Date().getMonth()<new Date(dob).getMonth()||new Date().getMonth()===new Date(dob).getMonth()&&new Date().getDate()<new Date(dob).getDate()?1:0));onComplete({id:`patient-${uid().slice(0,8)}`,name:clean,age,initials:initials||'NP',patientCode:`CS-${Date.now().toString().slice(-6)}`,phone,preferredLanguage:'English',address:'',emergencyContact:{name:'',phone:''},abhaLinked:false,allergiesStatus:'unknown',currentMedicines:'Not recorded'})}}>Create patient profile <ArrowRight size={17}/></button><p className="fine">No OTP is sent. Your information stays on this device.</p></section><button className="text-button emergency-text" onClick={onBack}><CalendarDays size={16}/>I already have an appointment</button></main>
}
