'use client';
import React,{useState} from 'react';
import {ArrowLeft,ArrowRight,CalendarDays,HeartPulse,UserPlus} from 'lucide-react';

type RegistrationDetails={name:string;phone:string;dob:string;gender:string};
export default function RegistrationScreen({onBack,onComplete}:{onBack:()=>void;onComplete:(details:RegistrationDetails)=>void}){
  const [name,setName]=useState('');const [phone,setPhone]=useState('');const [dob,setDob]=useState('');const [gender,setGender]=useState('');const [error,setError]=useState('');
  const today=new Date().toISOString().slice(0,10);
  const submit=()=>{const digits=phone.replace(/\D/g,'');if(!name.trim()){setError('Enter the patient’s full name.');return}if(!/^\d{10}$/.test(digits)){setError('Enter a valid 10-digit mobile number.');return}if(!dob||dob>today){setError('Date of birth cannot be in the future.');return}if(!gender){setError('Select a gender option or Prefer not to say.');return}const age=new Date().getFullYear()-new Date(dob).getFullYear();if(age<0||age>120){setError('Enter a realistic date of birth.');return}setError('');onComplete({name:name.trim(),phone:digits,dob,gender})};
  return <main className="auth-page registration-page"><div className="auth-brand"><div className="brand-mark"><HeartPulse size={25}/></div><strong>CareSetu<span>Your story. Better care.</span></strong></div><section className="card auth-card registration-card"><button className="text-button" onClick={onBack}><ArrowLeft size={15}/>Back to entry options</button><div className="question-icon"><UserPlus/></div><span className="eyebrow">NEW PATIENT PROFILE</span><h1>Create your CareSetu profile</h1><p>Create your profile and complete your case before your first visit.</p><label className="field"><span>Full name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Ishant Kumar" required/></label><label className="field"><span>Mobile number</span><input value={phone} onChange={e=>setPhone(e.target.value.replace(/\D/g,'').slice(0,10))} inputMode="numeric" maxLength={10} placeholder="10-digit number" required/></label><div className="form-grid"><label className="field"><span>Date of birth</span><input type="date" max={today} value={dob} onChange={e=>setDob(e.target.value)} required/></label><label className="field"><span>Gender</span><select value={gender} onChange={e=>setGender(e.target.value)} required><option value="">Select</option><option>Female</option><option>Male</option><option>Non-binary</option><option>Prefer not to say</option></select></label></div>{error&&<p className="error" role="alert">{error}</p>}<button className="button" onClick={submit}>Create profile <ArrowRight size={17}/></button><p className="fine">No OTP is sent and this profile is stored in your browser.</p></section><button className="text-button emergency-text" onClick={onBack}><CalendarDays size={16}/>I already have an appointment</button></main>
}
