export type Doctor={id:string;name:string;initials:string;department:string;specialization?:string;qualification:string;languages:string;phone?:string;email?:string;availableDays?:string[];availableFrom?:string;availableTo?:string;building?:string;room:string;floor:string;color:string;status?:'available'|'on-leave'|'offline'};
export const doctors:Doctor[]=[
{id:'meera',name:'Dr. Meera Sharma',initials:'MS',department:'General Medicine',specialization:'General Medicine',qualification:'MD · General Medicine',languages:'English, हिन्दी',phone:'+91 81111 10001',email:'meera.demo@example.test',availableDays:['Monday','Tuesday','Wednesday','Thursday','Friday'],availableFrom:'09:00',availableTo:'13:00',building:'CareSetu Block A',room:'204',floor:'2',color:'mint',status:'available'},
{id:'arjun',name:'Dr. Arjun Desai',initials:'AD',department:'Cardiology',specialization:'Cardiology',qualification:'DM · Cardiology',languages:'English, मराठी',phone:'+91 81111 10002',email:'arjun.demo@example.test',availableDays:['Monday','Wednesday','Friday'],availableFrom:'10:00',availableTo:'14:00',building:'CareSetu Block A',room:'302',floor:'3',color:'blue',status:'available'},
{id:'ananya',name:'Dr. Ananya Sen',initials:'AS',department:'Dermatology',specialization:'Dermatology',qualification:'MD · Dermatology',languages:'English, বাংলা',phone:'+91 81111 10003',email:'ananya.demo@example.test',availableDays:['Tuesday','Thursday','Saturday'],availableFrom:'09:30',availableTo:'12:30',building:'CareSetu Block B',room:'108',floor:'1',color:'lavender',status:'available'},
{id:'vikram',name:'Dr. Vikram Rao',initials:'VR',department:'Orthopedics',specialization:'Orthopedics',qualification:'MS · Orthopedics',languages:'English, தமிழ்',phone:'+91 81111 10004',email:'vikram.demo@example.test',availableDays:['Monday','Tuesday','Thursday','Friday'],availableFrom:'11:00',availableTo:'15:00',building:'CareSetu Block B',room:'206',floor:'2',color:'sand',status:'available'},
{id:'priya',name:'Dr. Priya Nair',initials:'PN',department:'Ayurveda',specialization:'Ayurveda',qualification:'MD · Ayurveda',languages:'English, हिन्दी, தமிழ்',phone:'+91 81111 10005',email:'priya.demo@example.test',availableDays:['Monday','Wednesday','Saturday'],availableFrom:'09:00',availableTo:'12:00',building:'CareSetu Block C',room:'105',floor:'1',color:'mint',status:'available'},
{id:'kabir',name:'Dr. Kabir Ali',initials:'KA',department:'Emergency Medicine',specialization:'Emergency Medicine',qualification:'MD · Emergency Medicine',languages:'English, हिन्दी',phone:'+91 81111 10006',email:'kabir.demo@example.test',availableDays:['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],availableFrom:'00:00',availableTo:'23:59',building:'CareSetu Block E',room:'E01',floor:'Ground',color:'rose',status:'available'}];
export type Patient={id:string;name:string;age:number;initials:string;patientCode?:string;phone?:string;email?:string;preferredLanguage?:string;address?:string;emergencyContact?:{name:string;phone:string};abhaLinked?:boolean;allergiesStatus?:string;currentMedicines?:string};
export const patients:Patient[]=[{id:'ramesh',name:'Ishant Kumar',age:42,initials:'IK',patientCode:'CS-DEMO-001',phone:'+91 90000 00001',email:'ishant.demo@example.test',preferredLanguage:'English',address:'New Delhi, India',emergencyContact:{name:'Meena Kumar',phone:'+91 90000 00002'},abhaLinked:false,allergiesStatus:'unknown',currentMedicines:'No current medicines reported'},{id:'asha',name:'Asha Verma',age:58,initials:'AV',patientCode:'CS-DEMO-002',phone:'+91 90000 00003',email:'asha.demo@example.test',preferredLanguage:'हिन्दी',address:'Lucknow, Uttar Pradesh',emergencyContact:{name:'Nisha Verma',phone:'+91 90000 00004'},abhaLinked:false,allergiesStatus:'reported',currentMedicines:'Vitamin D reported; dose needs confirmation'},{id:'dev',name:'Dev Patel',age:31,initials:'DP',patientCode:'CS-DEMO-003',phone:'+91 90000 00005',email:'dev.demo@example.test',preferredLanguage:'English',address:'Ahmedabad, Gujarat',emergencyContact:{name:'Riya Patel',phone:'+91 90000 00006'},abhaLinked:false,allergiesStatus:'unknown',currentMedicines:'Medication list needs reconciliation'}];
export type Observation={id:string;patientId:string;date:string;height:number;weight:number;source:string;systolic?:number;diastolic?:number;pulse?:number;temperature?:number;oxygen?:number};
export type Report={id:string;visitId:string;name:string;date:string;type:string;fixture?:boolean;data?:string;extracted?:string;verified?:boolean};
export type Visit={id:string;patientId:string;doctorId:string;date:string;time:string;reason:string;status:string;token?:string;priority:string;provisional:string;summary?:string;approved?:string;followup?:string;activity:string[];versions?:string[]};
export type State={observations:Observation[];visits:Visit[];reports:Report[];answers:Record<string,Record<string,string>>;intakeStep:Record<string,number>;rooms:Record<string,string>;notifications:string[];nextToken:number;selectedPatient:string;patients?:Patient[]};
export const day=(offset=0)=>{const d=new Date();d.setDate(d.getDate()+offset);return d.toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'})};
export const bmi=(height:number,weight:number)=>Number.isFinite(height)&&Number.isFinite(weight)&&height>0&&weight>0?weight/(height/100)**2:null;
export function seed():State{return {selectedPatient:'ramesh',patients,observations:[-75,-60,-45,-30,-15,0].map((n,i)=>({id:'obs'+i,patientId:'ramesh',date:day(n),height:170,weight:[67,66.4,66.7,65.8,65.3,65][i],source:'Patient-reported'})),visits:[
{id:'current',patientId:'ramesh',doctorId:'meera',date:day(),time:'10:30',reason:'Fatigue and sleep concerns',status:'confirmed',priority:'Unassessed',provisional:'Unassessed',activity:['Appointment confirmed']},
{id:'past-1',patientId:'ramesh',doctorId:'meera',date:day(-28),time:'11:00',reason:'General health consultation',status:'completed',priority:'Routine priority',provisional:'Unassessed',approved:'Patient attended a general health consultation. Patient-reported history was reviewed. No examination findings are included in this fictional record.',followup:'Bring previous reports to your next consultation.',activity:['Checked in','Summary reviewed by Dr. Meera Sharma','Visit completed']},
{id:'past-2',patientId:'ramesh',doctorId:'arjun',date:day(-65),time:'09:30',reason:'Follow-up consultation',status:'completed',priority:'Routine priority',provisional:'Unassessed',approved:'Previous history discussed with the patient. This is a fictional demonstration record.',activity:['Visit completed']},
{id:'asha-current',patientId:'asha',doctorId:'meera',date:day(),time:'10:00',reason:'Assisted intake — history incomplete',status:'waiting',token:'MED-021',priority:'Moderate priority',provisional:'Unassessed',activity:['Assisted by caregiver; details pending']},
{id:'dev-current',patientId:'dev',doctorId:'meera',date:day(),time:'10:15',reason:'Fictional urgent concern scenario',status:'checked-in',priority:'Unassessed',provisional:'Urgent concern',activity:['Demo concern raised — awaiting staff acknowledgment']}
],reports:[{id:'report1',visitId:'past-1',name:'Consultation note.pdf',date:day(-28),type:'application/pdf',fixture:true,extracted:'Fictional consultation note. Patient: Ishant Kumar. Document type: consultation note. Investigation values: not supplied. Current medicines: not confirmed.'},{id:'report2',visitId:'past-2',name:'Previous visit note.pdf',date:day(-65),type:'application/pdf',fixture:true,extracted:'Fictional follow-up record. Patient: Ishant Kumar. Clinical findings: not supplied.'}],answers:{ramesh:{consent:'I agree to fictional demo intake',complaint:'I have been feeling tired and not sleeping well.'}},intakeStep:{ramesh:2},rooms:{},notifications:['Your appointment with Dr. Meera Sharma is confirmed.'],nextToken:23};}
export const KEY='medikiosk-fictional-demo-v1';
export const doctorFor=(id:string)=>doctors.find(d=>d.id===id)!;
export const patientFor=(id:string)=>patients.find(p=>p.id===id)!;
export const makeSummary=(answers:Record<string,string>)=>Object.entries(answers).filter(([k,v])=>k!=='consent'&&v).map(([k,v])=>`${k}: ${v} [Source: intake answer · ${k}]`).join('\n\n');

export const uid=()=>typeof crypto.randomUUID==="function"?crypto.randomUUID():Array.from(crypto.getRandomValues(new Uint8Array(16))).map(n=>n.toString(16).padStart(2,"0")).join("");
